.\" manpage for myps
.\" Contact t.me/savchuk_vlad to correct errors or typos
.TH myps 1 "16 April 2021" "version 1.0" "myps manpage"

.SH NAME
.B myps
- відображення характеристик наявних у системі процесів.

.SH SYNOPSIS
.B myps
.RI "[" опції_вибору "] [" опції_формату "]..."

.SH DESCRIPTION
.B myps
виводить значення заданих характеристик процесів, вибраних за допомогою заданого критерію.

Критерій вибору задається секцією
.RI "["опції_вибору ].
Перелік характеристик задається секцією
.RI "["опції_формату ].
Як секція 
.RI "["опції_вибору ],
так і секція
.RI "["опції_формату ]
можуть бути порожніми. Якщо якась із них порожня, приймається її значення по замовчанню. 
Інформація виводиться у вигляді таблиці, кожний рядок якої містить значення заданих характеристик окремого процесу,
а кожна колонка - значення окремої характеристики.
.PP

.SH OPTIONS
.B "Перелік опцій вибору та їх опис:"
.TP
.B -Y, --select
указує на те, що результуючий критерій треба застосовувати прямо (вибирати ті процеси, які задовільняють критерію).
.TP
.B -N, --deselect
указує на те, що результуючий критерій треба інвертувати (вибирати ті процеси, які не задовільняють критерію).
.TP
.B -S, --current-sid
усі процеси із значенням SID, що збігається із значенням ідентифікатора поточного сеансу.
.TP
.B -C, --cmd [ім'я команди]
усі процеси із заданим (коротким) іменем команди.
.TP
.B -U, --User [номер або ім'я реального власника-користувача]
усі процеси із заданим реальним власником-користувачем.
.TP
.B -T, --current-tty
усі процеси з номером управляючого терміналу, що збігається з номером управляючого терміналу, асоційованого з поточним сеансом.
.TP
.B -D, --no-deamons
усі недемони (процеси, з якими асоційовано управляючий термінал).
.TP
Режим по замовчанню:
.I --select --current-sid.

.TP
.B "Перелік опцій формату та їх опис:"
.TP
.B -d, --default
eквівалент: --pid --cmdline (формат по замовчанню).
.TP
.B -m, --mem
еквівалент: --pid --size --rssize --shssize --tssize -dssize --sssize.
.TP
.B -p, --pid
виводити значення PID.
.TP
.B -P, --ppid
виводити значення PPID.
.TP
.B -C, --cmd
виводити ім'я команди.
.TP
.B -G, --Group
виводити значення GID або ім'я реального власника-групи (в залежності від наявності опції --names (-n)). По замовчанню - значення GID.
.TP
.B -T, --ttynum
виводити номер асоційованого з процесом управляючого терміналу.
.TP
.B -c, --path
виводити (абсолютне) ім'я виконуваного файлу.
.TP
.B --starttime
виводити час створення (у секундах відносно моменту ініціалізації системного таймера).
.TP
.B --vmstk
виводити розмір сегмента стеку (у кілобайтах).
.TP
.B --sigcgt
виводити набір сигналів, що перехоплюються (у вигляді шістнадцяткового числа).
.TP
.B -n, --names
замість значень UID, EUID, GID, EGID виводити відповідні імена.
.TP
.B --no-headers
не виводити заголовки.
.TP
Режим по замовчанню:
.I -- --default.

.SH EXAMPLES
.TP
.BR "myps"
Виводить значення PID і командний рядок усіх процесів, які мають SID, що збігається з ідентифікатором поточного сеансу.

.TP
.BR "myps -- --pid --ppid --cmd"
Виводить значення PID та PPID, а також ім'я команди усіх процесів, які мають SID, що збігається з ідентифікатором поточного сеансу.

.TP
.BR "myps -N --current-sid -- --pid -G"
Виводить PID та GUID усіх процесів, окрім тих, які мають SID, що не збігається з ідентифікатором поточного сеансу.

.SH EXIT STATUS
Повертає 0, якщо при отриманні інформації не виникло помилок, 1 - в іншому випадку.


.SH AUTHOR
Vlad Savchuk (github.com/1Lorde)

.SH COPYRIGHT
MIT License

.PP
Copyright (c) 2021 Vlad Savchuk
